### ISSUE TITLE
请问除了看你这个笔记之外，想要通过n2还需要做哪些方面的学习？希望能得到前辈的经验

### ISSUE THREAD

**Issue by Liufour** [xinwu-yang/nippon#17]

**Comment by xinwu-yang** [comment]
@Liufour 

感谢你的提问！

单纯通过考试的话，我的经验主要还是刷题，历年真题全部刷一边，首先可以熟悉题型，通过刷题还能摸清楚自己的不足，从而达到查漏补缺的效果！对我来说难度最高的是听力，我发挥不太稳定，所以会有针对性的练习！
